# This rule is not used by the project osc-s3-populator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over storage.populator.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osc-s3-populator
    app.kubernetes.io/managed-by: kustomize
  name: outscales3populator-admin-role
rules:
- apiGroups:
  - storage.populator.io
  resources:
  - outscales3populators
  verbs:
  - '*'
- apiGroups:
  - storage.populator.io
  resources:
  - outscales3populators/status
  verbs:
  - get
