# This rule is not used by the project osc-s3-populator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the storage.populator.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osc-s3-populator
    app.kubernetes.io/managed-by: kustomize
  name: outscales3populator-editor-role
rules:
- apiGroups:
  - storage.populator.io
  resources:
  - outscales3populators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.populator.io
  resources:
  - outscales3populators/status
  verbs:
  - get
