# This rule is not used by the project osc-s3-populator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to storage.populator.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: osc-s3-populator
    app.kubernetes.io/managed-by: kustomize
  name: outscales3populator-viewer-role
rules:
- apiGroups:
  - storage.populator.io
  resources:
  - outscales3populators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - storage.populator.io
  resources:
  - outscales3populators/status
  verbs:
  - get
